### ISSUE TITLE
Instructions for 21:9?

### ISSUE THREAD

**Issue by johnzfitch** [Skip-eo/Deadlock-Config#1]
Just wanted to say thanks for the config! Any chance you'll add details on this? Impatiently waiting LOL @Skip-eo 

> Turns out the game currently increases and decreases your horizontal FOV depending on your aspect ratio. By configuring your video.txt file to only reduce your vertical res, but keep your horizontal the same, you can increase your fov by ~20% (from default 75FOV at 16:9 to ~99FOV at 21:9).

> ADD INSTRUCTIONS HERE

**Comment by Skip-eo** [comment]
Glad you're liking the config! I'm in the process of writing up the documentation for this. Should have atleast a basic writeup in the next day.

**Comment by Skip-eo** [comment]
@johnzfitch complete

**Comment by johnzfitch** [comment]
@Skip-eo Thank you! Easy to follow and I appreciate the time you took to do some screenshots. Is this only relevant for folks who don't have a 21:9 monitor? 

What if you were to stretch it further on a 3440x1440 monitor?
![image](https://github.com/user-attachments/assets/26c7ecfb-d70d-49ae-b9e0-454cfd2721db)

**Comment by Skip-eo** [comment]
This guide is intended for 16:9 players yes. Given players have gotten 4:3 to work ingame (which isn't officially supported by deadlock) I don't see why you couldn't go further...
